version: '3'
services:
   python3_wiki:
     env_file: .env
     build:
       context: .
       args:
         UID: $UID
         GID: $GID
     container_name: 'python3_wiki'
     restart: always
     working_dir: '/opt/working'
     tty: true
     volumes:
        - ./working:/opt/working
        - ../web_container/html:/var/www/html
